[package]
name = "grisui-prelude-game"
version = "0.1.0"
authors = ["Yoan Lecoq <yoanlecoq.io@gmail.com>"]

[dependencies]
sdl2 = { version="0.31.0", features=["mixer", "ttf"] }
gl = "0.7.0"
log = "0.4.0-rc.1"
env_logger="0.5.0-rc.1"
